### ISSUE TITLE
sample.cache_all() breaks analysis by sample set order

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#239]
After re-running bootstrap, tis, and then running analysis, I added `storage.samples.cache_all()`, first to the `retis.all_statistics` function, then (after getting this same error) I tried putting the `cache_all` call directly in the notebook instead. Analysis without `cache_all()` works fine. The `cache_all()` function runs fine, but if I try to run the analysis `retis.all_statistics()` after running `cache_all`, I get the following:

```
/Users/dwhs/Dropbox/msm-tis/openpathsampling/analysis/tis_analysis.pyc in sampleset_sample_generator(storage)
     60 
     61 def sampleset_sample_generator(storage):
---> 62     for sset in storage.samplesets:
     63         for sample in sset:
     64             yield sample

/Users/dwhs/Dropbox/msm-tis/openpathsampling/storage/object_storage.pyc in next(self)
    413             def next(self):
    414                 if self.idx < self.end:
--> 415                     obj = self.storage.load(self.idx)
    416                     if self.iter_range is not None and self.iter_range.step is not None:
    417                         self.idx += self.iter_range.step

/Users/dwhs/Dropbox/msm-tis/openpathsampling/storage/object_storage.pyc in inner(self, idx, *args, **kwargs)
   1098         # the class method directly it is not bound yet and so we need to include the self! Took me some time to
   1099         # understand and figure that out
-> 1100         obj = func(n_idx, *args, **kwargs)
   1101         if obj is not None:
   1102             # update cache there might have been a change due to naming

/Users/dwhs/Dropbox/msm-tis/openpathsampling/storage/object_storage.pyc in inner(self, idx, *args, **kwargs)
   1167             return None
   1168         else:
-> 1169             obj = func(n_idx, *args, **kwargs)
   1170 
   1171         if not hasattr(obj, 'idx'):

/Users/dwhs/Dropbox/msm-tis/openpathsampling/storage/sample_store.pyc in load(self, idx)
    212         # typecast to sample
    213         samples = self.list_from_numpy(values, 'samples')
--> 214         sample_set = SampleSet(samples, movepath=self.storage.pathmovechanges.load(movepath_idx))
    215 
    216         return sample_set

/Users/dwhs/Dropbox/msm-tis/openpathsampling/sample.pyc in __init__(self, samples, movepath)
     46         self.ensemble_dict = {}
     47         self.replica_dict = {}
---> 48         self.extend(samples)
     49         if movepath is None:
     50             self.movepath = paths.EmptyPathMoveChange()

/Users/dwhs/Dropbox/msm-tis/openpathsampling/sample.pyc in extend(self, samples)
    138         try:
    139             for sample in samples:
--> 140                 self.append(sample)
    141         except TypeError:
    142             # also acts as .append() if given a single sample

/Users/dwhs/Dropbox/msm-tis/openpathsampling/sample.pyc in append(self, sample)
    127             self.ensemble_dict[sample.ensemble].append(sample)
    128         except KeyError:
--> 129             self.ensemble_dict[sample.ensemble] = [sample]
    130         try:
    131             self.replica_dict[sample.replica].append(sample)

/Users/dwhs/Dropbox/msm-tis/openpathsampling/storage/object_storage.pyc in _getattr(this, item)
    156                             _loader = cls._delayed_loading[item]
    157 #                            print 'from', repr(self.storage), id(self), 'and not', repr(this), 'load', item
--> 158                             _loader(this)
    159                         else:
    160                             raise KeyError(item)

/Users/dwhs/Dropbox/msm-tis/openpathsampling/storage/object_storage.pyc in updater(obj)
   1236     """
   1237     def updater(obj):
-> 1238         storage = obj._origin
   1239 
   1240         idx = obj.idx[storage]

/Users/dwhs/Dropbox/msm-tis/openpathsampling/storage/object_storage.pyc in _getattr(this, item)
    158                             _loader(this)
    159                         else:
--> 160                             raise KeyError(item)
    161 
    162                     return this.__dict__[item]

KeyError: '_origin'
```

**Comment by jhprinz** [comment]
My fault. The fast caching is a little tricky and delayed loaded attributes need a reference to the storage where they should load from. I made a PR to fix that.

**Comment by dwhswenson** [comment]
Should have been fixed by #240.

**Comment by dwhswenson** [comment]
Spoke to soon. There's still a bug here, although it has moved. It looks to me like the `sample.trajectory` object is not available if we loaded the samples with `storage.sample.cache_all()`. (See traceback below.)

Please do the following: in the `toy_analysis.ipynb` notebook, change the cell

```python
%%time
retis.all_statistics(storage=storage, weights=None, force=True)
```

to 

```python
%%time
storage.samples.cache_all()
retis.all_statistics(storage=storage, weights=None, force=True)
```

Run that notebook as a test (you can skip running the `move_summary` lines to speed it up). Until the changed cell runs without error, this bug is still open.

Here's the traceback I'm getting:

```
/Users/dwhs/Dropbox/msm-tis/openpathsampling/analysis/tis_analysis.pyc in all_statistics(self, storage, weights, force)
    417         for ens in self.ensembles:
    418             samples = sampleset_sample_generator(storage)
--> 419             self.ensemble_statistics(ens, samples, weights, force)
    420 
    421     def pathlength_histogram(self, ensemble):

/Users/dwhs/Dropbox/msm-tis/openpathsampling/analysis/tis_analysis.pyc in ensemble_statistics(self, ensemble, samples, weights, force)
    398             for hist in run_it:
    399                 hist_info = self.ensemble_histogram_info[hist]
--> 400                 hist_data_sample = hist_info.f(sample, **hist_info.f_args)
    401                 try:
    402                     hist_data[hist].append(hist_data_sample)

/Users/dwhs/Dropbox/msm-tis/openpathsampling/analysis/tis_analysis.pyc in max_lambdas(sample, orderparameter)
     57 
     58 def max_lambdas(sample, orderparameter):
---> 59     return max([orderparameter(frame) for frame in sample.trajectory])
     60 
     61 def sampleset_sample_generator(storage):

TypeError: 'NoneType' object is not iterable
```

**Comment by jhprinz** [comment]
Found the stupid bug. Man, the problem is that the new method loads all trajectory indices and loads the trajectories. But the number is a numpy.int and the load function does not work with this and returns None. Will make a better fix...

**Comment by jhprinz** [comment]
I think this is fixed and will close it.

**Comment by dwhswenson** [comment]
When was this fixed? The last PR merged to master from you was #240, which did NOT fix it. When I run this on master, I still get the error listed above.

**Comment by jhprinz** [comment]
shoot. That was my fault. I fixed it and added this to the branch the add the fast loading of PMCs. I will make a new PR and add the fixes to get this working quickly. Sorry for the problem. I had that already fixed in my mind...

**Comment by dwhswenson** [comment]
As of #253, looks like this is solved.
